baseURL = "/"
languageCode = "en-us"
title = "Minimal"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Calin Tataru"
    description = "Personal blog theme powered by Hugo"
    githubUsername = "#"
    accent = "maroon"
    showBorder = true
    backgroundColor = "#f5f5f5"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "atelier-heath-light" # make this complement accent color!
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift", "r"]

# adjust these as you see fit
[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3
    
[[menu.main]]
    url = "/tags/"
    name = "Tags"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:me@example.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/username/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/username/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/username/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.stackoverflow.com/username/"
    name = "stack-overflow"
    weight = 5